apiVersion: batch/v1
kind: CronJob
metadata:
  name: descheduler-multiobjective
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 1
  
  concurrencyPolicy: Forbid
  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: descheduler-multiobjective
        spec:
          serviceAccountName: descheduler
          restartPolicy: OnFailure
          
          # Use node affinity to run on control plane if desired
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
          
          tolerations:
          # Tolerate control plane taints
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          
          containers:
          - name: descheduler
            image: paravirtualtishu/descheduler:1.0.0-arm64
            command:
            - "/bin/descheduler"
            args:
            - "--policy-config-file=/policy/policy.yaml"
            - "--v=2"

            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            
            volumeMounts:
            - name: policy-config
              mountPath: /policy
              readOnly: true
          
          volumes:
          - name: policy-config
            configMap:
              name: descheduler-policy-configmap
