apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedulinghints.descheduler.io
spec:
  group: descheduler.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              hints:
                type: array
                items:
                  type: object
                  required:
                  - podName
                  - podNamespace
                  - targetNode
                  properties:
                    podName:
                      type: string
                    podNamespace:
                      type: string
                    targetNode:
                      type: string
                    priority:
                      type: integer
                      default: 100
                    reason:
                      type: string
              expirationTime:
                type: string
                format: date-time
              deschedulerGeneration:
                type: integer
          status:
            type: object
            properties:
              appliedHints:
                type: array
                items:
                  type: object
                  properties:
                    podName:
                      type: string
                    appliedAt:
                      type: string
                      format: date-time
  scope: Cluster
  names:
    plural: schedulinghints
    singular: schedulinghint
    kind: SchedulingHint
