apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: MultiObjectiveProfile
    pluginConfig:
    - name: "MultiObjective"
      args:
        weights:
          cost: 0.90
          disruption: 0.10
          balance: 0.00
    plugins:
      balance:
        enabled:
          - "MultiObjective"  
